apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: sjm-tastpa-6 
  janus-idp.io/tekton: sjm-tastpa-6
  backstage.io/kubernetes-id: sjm-tastpa-6
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sjm-tastpa-6
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml