apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sjm-tastpa-6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sjm-tastpa-6 
  name: sjm-tastpa-6
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sjm-tastpa-6 
